server:
  #端口号
  port: 8080

#配置使用上线的配置文件(或本地使用的配置文件)
#数据库连接的配置因为在本地和线上不同所以单独配置在dev或prod中
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usernew?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  #配置JPA
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect